name: Build Windows Executable

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9 (64-bit)
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'
        
    - name: Install dependencies
      run: |
        # Install only what we need (no TWAIN DSM attempt)
        python -m pip install --upgrade pip
        pip install pyqt5==5.15.7 pywin32==306 pillow==9.5.0 pyinstaller==5.13.0
        
    - name: Build with PyInstaller
      run: |
        # Get PyQt5 path dynamically
        $PYQT_PATH = python -c "import os, PyQt5; print(os.path.dirname(PyQt5.__file__))"
        
        # Simplified build command
        pyinstaller --noconfirm --clean --log-level DEBUG `
          --onefile --windowed `
          --add-data "$PYQT_PATH/Qt/plugins/platforms/*;platforms/" `
          --add-data "$PYQT_PATH/Qt/plugins/imageformats/*;imageformats/" `
          --hidden-import PyQt5.QtCore `
          --hidden-import PyQt5.QtGui `
          --hidden-import PyQt5.QtWidgets `
          scanner_app.py
        
        # Verify build
        if (Test-Path -Path "dist\scanner_app.exe") {
            echo "Build successful!"
        } else {
            echo "::error::Build failed"
            Get-Content "build\scanner_app\warn-scanner_app.txt" | Write-Host
            exit 1
        }
        
    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ScannerApp
        path: dist/scanner_app.exe
